import pandas as pd
from pathlib import Path

current_dir = Path(__file__).parent
df = pd.read_csv(current_dir / "walmart_cleaned_data.csv", parse_dates=['Date'])

# --- TIME SERIES PREPARATION ---
# Sort by Store and Date to ensure correct lag calculations
df = df.sort_values(by=['Store', 'Date'])

# --- LAG FEATURES ---
# Lag 1: Sales from the previous week
df['Sales_Lag_1'] = df.groupby('Store')['Weekly_Sales'].shift(1)

# Lag 4: Sales from 4 weeks ago
df['Sales_Lag_4'] = df.groupby('Store')['Weekly_Sales'].shift(4)

# Lag 52: Sales from 52 weeks ago
df['Sales_Lag_52'] = df.groupby('Store')['Weekly_Sales'].shift(52)

# --- ROLLING MEAN ---
# Captures the general trend by smoothing out weekly fluctuations (Noise Reduction).
# Note: Calculated on 'Sales_Lag_1' to prevent data leakage (future peeking).
df['Sales_MA4'] = df.groupby('Store')['Sales_Lag_1'].transform(lambda x: x.rolling(window=4).mean())

# Inspection
print("\nSample Data (Check Lag & Moving Average):")
print(df[['Date', 'Store', 'Weekly_Sales', 'Sales_Lag_1', 'Sales_MA4']].iloc[40:45])

# --- EVENT COUNTDOWN FEATURES ---

# A.Weeks to Christmas (Target: Week 52)
def calculate_weeks_to_christmas(week_number):
    if week_number < 52:
        return 52 - week_number
    else:
        return 0

df['Weeks_to_Christmas'] = df['Week'].apply(calculate_weeks_to_christmas)

# B. Weeks to Thanksgiving / Black Friday (Target: Week 47)
def calculate_weeks_to_thanksgiving(week_number):
    black_friday_week = 47
    if week_number <= black_friday_week:
        return black_friday_week - week_number
    else:
        return 0
    
df['Weeks_to_Thanksgiving'] = df['Week'].apply(calculate_weeks_to_thanksgiving)

# --- DATA CLEANING ---
# Drop rows with NaN values generated by Lag_52 (First year of data)
initial_shape = df.shape
df = df.dropna()
final_shape = df.shape

print(f"Dropped rows: {initial_shape[0] - final_shape[0]}")
print(f"Data ready! New Columns: Sales_Lag_1, Sales_Lag_4, Sales_Lag_52, Sales_MA4, Weeks_to_Christmas, Weeks_to_Thanksgiving")

# Save Final Dataset
output_path = current_dir / "final_train_data.csv"
df.to_csv(output_path, index=False)
print(f"\nSUCCESS: Engineered data saved to: {output_path}")

# Final Check
print("\nCheck Data (Approaching Thanksgiving):")
print(df[(df['Week'] >= 43) & (df['Week'] <= 47)][['Date', 'Week', 'Weeks_to_Thanksgiving', 'Weekly_Sales']].head(5))